app:
  asl_version: v0.1
  work_dir:
    - home
    - home/container
    - home/status
    - bin
    - include
    - lib
    - libexec
    - tmp
  default_mode: unshare
  mount_partitions:
    - /
    - /proc
    - /sys
    - /dev
    - /dev/shm
    - /dev/pts
    - /dev/fd
    - /dev/tty
    - /dev/net/tun
    - /proc/sys/fs/binfmt_misc
    - /sdcard
  is_debug: true
  is_filelogging: false

linux:
  path:
    - $ASL_TOOLKIT
    - $ASL_TOOLKIT/busybox
    - $PATH
  ld_library_path+: :$ASL_LIB
  proot_tmp_dir: $ASL_TMP
  proot_loader: $ASL_LIBEXEC/libloader.so

deploy:
  initial_sequence:
    - hosts
    - hostname
    - timezone
    - net
    - user
    - sudo
    - aid
  later_sequence:
    - ssh
  is_create_user: true
  user_name: yaoxiaonie
  user_password: asl123456
  privileged_users:
    - "$USER_NAME:aid_inet"
    - "$USER_NAME:aid_sdcard_rw"
    - "$USER_NAME:aid_graphics"