# 此配置将在ASL启动时被读取
app:
  # ASL程序版本
  ASL_VERSION: v0.1
  WORK_DIR:
    - home
    - home/container
    - home/status
    - bin
    - include
    - lib
    - libexec
    - tmp
  # ASL工作模式 proot & unshare
  DEFAULT_MODE: unshare
  # ASL容器分区挂载
  MOUNT_PARTITIONS:
    - /
    - /proc
    - /sys
    - /dev
    - /dev/shm
    - /dev/pts
    - /dev/fd
    - /dev/tty
    - /dev/net/tun
    - /proc/sys/fs/binfmt_misc
    - /sdcard
  # ASL Debug LOG输出（true & false）
  IS_DEBUG: true
  IS_FILELOGGING: false

linux:
  # Linux Shell配置
  PATH:
    - $ASL_TOOLKIT
    - $ASL_TOOLKIT/busybox
    - $PATH
  LD_LIBRARY_PATH+: :$ASL_LIB
  # proot必要配置
  PROOT_TMP_DIR: $ASL_TMP
  PROOT_LOADER: $ASL_LIBEXEC/libloader.so

deploy:
  # 部署顺序
  INITIAL_SEQUENCE:
    - hosts
    - hostname
    - timezone
    - net
    - user
    - sudo
    - aid
  LATER_SEQUENCE:
    - ssh
  # 是否要创建用户（true & false）
  CREATE_USER: true
  # 用户名
  USER_NAME: yaoxiaonie
  # 用户密码
  USER_PASSWORD: asl123456
  # 特权用户权限
  PRIVILEGED_USERS:
    - "$USER_NAME:aid_inet"
    - "$USER_NAME:aid_sdcard_rw"
    - "$USER_NAME:aid_graphics"
